name = "project-vecmem-mcp-server"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "faiss-cpu>=1.12.0",
    "fastmcp>=2.12.4",
    "sentence-transformers>=5.1.1",
    "sqlite-utils>=3.38",
]
